///
///  ComplexTypeTests.swift
///
///  Copyright 2017 Tony Stone
///
///  Licensed under the Apache License, Version 2.0 (the "License");
///  you may not use this file except in compliance with the License.
///  You may obtain a copy of the License at
///
///  http://www.apache.org/licenses/LICENSE-2.0
///
///  Unless required by applicable law or agreed to in writing, software
///  distributed under the License is distributed on an "AS IS" BASIS,
///  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
///  See the License for the specific language governing permissions and
///  limitations under the License.
///
///  Created by Tony Stone on 10/6/17.
///
import XCTest
import TestFixtures

///
/// NOTE: This file was auto generated by gyb from file ComplexTypeTests.swift.gyb using the following command.
///
/// gyb --line-directive '' ComplexTypeTests.swift.gyb
///
/// Do NOT edit this file directly as it will be regenerated automatically when needed.  Modify ComplexTypeTests.swift.gyb instead.
///

///
/// ComplexClass tests.
///
/// - Note It's important to test the fixture so we can be confident that
///        when we use them for testing other parts of the system, we
///        are sure they are not causing an unwanted side affect or false
///        positve/negative.
///
class ComplexClassTests: XCTestCase {

    // MARK: - Test Initialization

    func testInitWithNoArguments() {
        let input = ComplexClass()
        let expected: (boolVar: Bool, intVar: Int, doubleVar: Double, stringVar: String, optionalStringVar: String?, objectVar: BasicClass, objectArrayVar: [BasicClass]) = (false, 0, 0.00, "", nil, BasicClass(), [])

        XCTAssertEqual(input.boolVar,           expected.boolVar)
        XCTAssertEqual(input.intVar,            expected.intVar)
        XCTAssertEqual(input.doubleVar,         expected.doubleVar)
        XCTAssertEqual(input.stringVar,         expected.stringVar)
        XCTAssertEqual(input.optionalStringVar, expected.optionalStringVar)
        XCTAssertEqual(input.objectVar,         expected.objectVar)
        XCTAssertEqual(input.objectArrayVar,    expected.objectArrayVar)

    }

    func testInitWithArguments() {
        let input = ComplexClass(boolVar: true, intVar: 10, doubleVar: 20.10, stringVar: "Test String", optionalStringVar: "Another Test String", objectVar: BasicClass(stringVar: "Test String"), objectArrayVar: [])
        let expected: (boolVar: Bool, intVar: Int, doubleVar: Double, stringVar: String, optionalStringVar: String?, objectVar: BasicClass, objectArrayVar: [BasicClass]) = (true, 10, 20.10, "Test String", "Another Test String", BasicClass(stringVar: "Test String"), [])

        XCTAssertEqual(input.boolVar,           expected.boolVar)
        XCTAssertEqual(input.intVar,            expected.intVar)
        XCTAssertEqual(input.doubleVar,         expected.doubleVar)
        XCTAssertEqual(input.stringVar,         expected.stringVar)
        XCTAssertEqual(input.optionalStringVar, expected.optionalStringVar)
        XCTAssertEqual(input.objectVar,         expected.objectVar)
        XCTAssertEqual(input.objectArrayVar,    expected.objectArrayVar)
    }

    // MARK: - Test Equal

    func testEqualWithNoArguments() {
        let input    = ComplexClass()
        let expected = ComplexClass(boolVar: false, intVar: 0, doubleVar: 0.00, stringVar: "", optionalStringVar: nil, objectVar: BasicClass(), objectArrayVar: [])

        XCTAssertEqual(input, expected)
    }

    func testEqualWithArguments() {
        let input     = ComplexClass(boolVar: true, intVar: 10, doubleVar: 20.10, stringVar: "Test String", optionalStringVar: "Another Test String", objectVar: BasicClass(stringVar: "Test String"), objectArrayVar: [])
        let expected  = ComplexClass(boolVar: true, intVar: 10, doubleVar: 20.10, stringVar: "Test String", optionalStringVar: "Another Test String", objectVar: BasicClass(stringVar: "Test String"), objectArrayVar: [])

        XCTAssertEqual(input, expected)
    }

    func testEqualDifferentBoolVar() {
        let input    = ComplexClass(boolVar: true)
        let expected = ComplexClass(boolVar: false)

        XCTAssertNotEqual(input, expected)
    }

    func testEqualDifferentIntVar() {
        let input    = ComplexClass(intVar: 10)
        let expected = ComplexClass(intVar: 0)

        XCTAssertNotEqual(input, expected)
    }

    func testEqualDifferentDoubleVar() {
        let input    = ComplexClass(doubleVar: 20.00)
        let expected = ComplexClass(doubleVar: 0.00)

        XCTAssertNotEqual(input, expected)
    }

    func testEqualDifferentStringVar() {
        let input    = ComplexClass(stringVar: "Test String")
        let expected = ComplexClass(stringVar: "")

        XCTAssertNotEqual(input, expected)
    }

    func testEqualDifferentOptionalStringVar() {
        let input    = ComplexClass(optionalStringVar: "Test String")
        let expected = ComplexClass(optionalStringVar: "")

        XCTAssertNotEqual(input, expected)
    }

    func testEqualDifferentOptionalStringVarWithNil() {
        let input    = ComplexClass(optionalStringVar: "Test String")
        let expected = ComplexClass(optionalStringVar: nil)

        XCTAssertNotEqual(input, expected)
    }

    func testEqualDifferentObjectVar() {
        let input    = ComplexClass(objectVar: BasicClass(stringVar: "Input"))
        let expected = ComplexClass(objectVar: BasicClass(stringVar: "Expected"))

        XCTAssertNotEqual(input, expected)
    }

    func testEqualDifferentObjectArrayVar() {
        let input    = ComplexClass(objectArrayVar: [BasicClass(stringVar: "Input")])
        let expected = ComplexClass(objectArrayVar: [BasicClass(stringVar: "Expected1"), BasicClass(stringVar: "Expected2")])

        XCTAssertNotEqual(input, expected)
    }

    // MARK: - Test Encoding

    func testEncode() throws {
        let input = ComplexClass(boolVar: true, intVar: 10, doubleVar: 20.10, stringVar: "Test String", optionalStringVar: "Another Test String", objectVar: BasicClass(stringVar: "Test String"), objectArrayVar: [])
        let expected = "{\"optionalStringVar\":\"Another Test String\",\"intVar\":10,\"objectArrayVar\":[],\"boolVar\":true,\"doubleVar\":20.1,\"objectVar\":{\"stringVar\":\"Test String\",\"intVar\":0,\"boolVar\":false,\"doubleVar\":0},\"stringVar\":\"Test String\"}"

        let result = String(data: try JSONEncoder().encode(input), encoding: .utf8)

        XCTAssertEqual(result, expected)
    }

    func testDecode() throws {
        let input = "{\"optionalStringVar\":\"Another Test String\",\"intVar\":10,\"objectArrayVar\":[],\"boolVar\":true,\"doubleVar\":20.1,\"objectVar\":{\"stringVar\":\"Test String\",\"intVar\":0,\"boolVar\":false,\"doubleVar\":0},\"stringVar\":\"Test String\"}".data(using: .utf8)
        let expected = ComplexClass(boolVar: true, intVar: 10, doubleVar: 20.10, stringVar: "Test String", optionalStringVar: "Another Test String", objectVar: BasicClass(stringVar: "Test String"), objectArrayVar: [])

        if let data = input {
            let result = try JSONDecoder().decode(ComplexClass.self, from: data)

            XCTAssertEqual(result, expected)
        } else {
            XCTFail()
        }
    }

    // MARK: - Test Description

    func testDescription() {
        let input = ComplexClass(boolVar: true, intVar: 10, doubleVar: 20.10, stringVar: "Test String", optionalStringVar: "Another Test String", objectVar: BasicClass(stringVar: "Test String"), objectArrayVar: [])
        let expected = "\(String(describing: ComplexClass.self))(boolVar: true, intVar: 10, doubleVar: 20.1, stringVar: \"Test String\", optionalStringVar: \"Another Test String\", objectVar: \(String(describing: BasicClass.self))(boolVar: false, intVar: 0, doubleVar: 0.0, stringVar: \"Test String\"), objectArrayVar: [])"

        XCTAssertEqual(input.description, expected)
    }
}

///
/// ComplexStruct tests.
///
/// - Note It's important to test the fixture so we can be confident that
///        when we use them for testing other parts of the system, we
///        are sure they are not causing an unwanted side affect or false
///        positve/negative.
///
class ComplexStructTests: XCTestCase {

    // MARK: - Test Initialization

    func testInitWithNoArguments() {
        let input = ComplexStruct()
        let expected: (boolVar: Bool, intVar: Int, doubleVar: Double, stringVar: String, optionalStringVar: String?, objectVar: BasicStruct, objectArrayVar: [BasicStruct]) = (false, 0, 0.00, "", nil, BasicStruct(), [])

        XCTAssertEqual(input.boolVar,           expected.boolVar)
        XCTAssertEqual(input.intVar,            expected.intVar)
        XCTAssertEqual(input.doubleVar,         expected.doubleVar)
        XCTAssertEqual(input.stringVar,         expected.stringVar)
        XCTAssertEqual(input.optionalStringVar, expected.optionalStringVar)
        XCTAssertEqual(input.objectVar,         expected.objectVar)
        XCTAssertEqual(input.objectArrayVar,    expected.objectArrayVar)

    }

    func testInitWithArguments() {
        let input = ComplexStruct(boolVar: true, intVar: 10, doubleVar: 20.10, stringVar: "Test String", optionalStringVar: "Another Test String", objectVar: BasicStruct(stringVar: "Test String"), objectArrayVar: [])
        let expected: (boolVar: Bool, intVar: Int, doubleVar: Double, stringVar: String, optionalStringVar: String?, objectVar: BasicStruct, objectArrayVar: [BasicStruct]) = (true, 10, 20.10, "Test String", "Another Test String", BasicStruct(stringVar: "Test String"), [])

        XCTAssertEqual(input.boolVar,           expected.boolVar)
        XCTAssertEqual(input.intVar,            expected.intVar)
        XCTAssertEqual(input.doubleVar,         expected.doubleVar)
        XCTAssertEqual(input.stringVar,         expected.stringVar)
        XCTAssertEqual(input.optionalStringVar, expected.optionalStringVar)
        XCTAssertEqual(input.objectVar,         expected.objectVar)
        XCTAssertEqual(input.objectArrayVar,    expected.objectArrayVar)
    }

    // MARK: - Test Equal

    func testEqualWithNoArguments() {
        let input    = ComplexStruct()
        let expected = ComplexStruct(boolVar: false, intVar: 0, doubleVar: 0.00, stringVar: "", optionalStringVar: nil, objectVar: BasicStruct(), objectArrayVar: [])

        XCTAssertEqual(input, expected)
    }

    func testEqualWithArguments() {
        let input     = ComplexStruct(boolVar: true, intVar: 10, doubleVar: 20.10, stringVar: "Test String", optionalStringVar: "Another Test String", objectVar: BasicStruct(stringVar: "Test String"), objectArrayVar: [])
        let expected  = ComplexStruct(boolVar: true, intVar: 10, doubleVar: 20.10, stringVar: "Test String", optionalStringVar: "Another Test String", objectVar: BasicStruct(stringVar: "Test String"), objectArrayVar: [])

        XCTAssertEqual(input, expected)
    }

    func testEqualDifferentBoolVar() {
        let input    = ComplexStruct(boolVar: true)
        let expected = ComplexStruct(boolVar: false)

        XCTAssertNotEqual(input, expected)
    }

    func testEqualDifferentIntVar() {
        let input    = ComplexStruct(intVar: 10)
        let expected = ComplexStruct(intVar: 0)

        XCTAssertNotEqual(input, expected)
    }

    func testEqualDifferentDoubleVar() {
        let input    = ComplexStruct(doubleVar: 20.00)
        let expected = ComplexStruct(doubleVar: 0.00)

        XCTAssertNotEqual(input, expected)
    }

    func testEqualDifferentStringVar() {
        let input    = ComplexStruct(stringVar: "Test String")
        let expected = ComplexStruct(stringVar: "")

        XCTAssertNotEqual(input, expected)
    }

    func testEqualDifferentOptionalStringVar() {
        let input    = ComplexStruct(optionalStringVar: "Test String")
        let expected = ComplexStruct(optionalStringVar: "")

        XCTAssertNotEqual(input, expected)
    }

    func testEqualDifferentOptionalStringVarWithNil() {
        let input    = ComplexStruct(optionalStringVar: "Test String")
        let expected = ComplexStruct(optionalStringVar: nil)

        XCTAssertNotEqual(input, expected)
    }

    func testEqualDifferentObjectVar() {
        let input    = ComplexStruct(objectVar: BasicStruct(stringVar: "Input"))
        let expected = ComplexStruct(objectVar: BasicStruct(stringVar: "Expected"))

        XCTAssertNotEqual(input, expected)
    }

    func testEqualDifferentObjectArrayVar() {
        let input    = ComplexStruct(objectArrayVar: [BasicStruct(stringVar: "Input")])
        let expected = ComplexStruct(objectArrayVar: [BasicStruct(stringVar: "Expected1"), BasicStruct(stringVar: "Expected2")])

        XCTAssertNotEqual(input, expected)
    }

    // MARK: - Test Encoding

    func testEncode() throws {
        let input = ComplexStruct(boolVar: true, intVar: 10, doubleVar: 20.10, stringVar: "Test String", optionalStringVar: "Another Test String", objectVar: BasicStruct(stringVar: "Test String"), objectArrayVar: [])
        let expected = "{\"optionalStringVar\":\"Another Test String\",\"intVar\":10,\"objectArrayVar\":[],\"boolVar\":true,\"doubleVar\":20.1,\"objectVar\":{\"stringVar\":\"Test String\",\"intVar\":0,\"boolVar\":false,\"doubleVar\":0},\"stringVar\":\"Test String\"}"

        let result = String(data: try JSONEncoder().encode(input), encoding: .utf8)

        XCTAssertEqual(result, expected)
    }

    func testDecode() throws {
        let input = "{\"optionalStringVar\":\"Another Test String\",\"intVar\":10,\"objectArrayVar\":[],\"boolVar\":true,\"doubleVar\":20.1,\"objectVar\":{\"stringVar\":\"Test String\",\"intVar\":0,\"boolVar\":false,\"doubleVar\":0},\"stringVar\":\"Test String\"}".data(using: .utf8)
        let expected = ComplexStruct(boolVar: true, intVar: 10, doubleVar: 20.10, stringVar: "Test String", optionalStringVar: "Another Test String", objectVar: BasicStruct(stringVar: "Test String"), objectArrayVar: [])

        if let data = input {
            let result = try JSONDecoder().decode(ComplexStruct.self, from: data)

            XCTAssertEqual(result, expected)
        } else {
            XCTFail()
        }
    }

    // MARK: - Test Description

    func testDescription() {
        let input = ComplexStruct(boolVar: true, intVar: 10, doubleVar: 20.10, stringVar: "Test String", optionalStringVar: "Another Test String", objectVar: BasicStruct(stringVar: "Test String"), objectArrayVar: [])
        let expected = "\(String(describing: ComplexStruct.self))(boolVar: true, intVar: 10, doubleVar: 20.1, stringVar: \"Test String\", optionalStringVar: \"Another Test String\", objectVar: \(String(describing: BasicStruct.self))(boolVar: false, intVar: 0, doubleVar: 0.0, stringVar: \"Test String\"), objectArrayVar: [])"

        XCTAssertEqual(input.description, expected)
    }
}

